config/routes.rb
SocialThing::Application.routes.draw do

  resources :users, :only => [:create, :new, :show] do
    resources :friend_circles, :only => [:new, :create, :edit, :update]
    resources :posts do
      resources :links, :only => [:create, :destroy]
    end

    member do
      get 'forgot_password'
      get 'feed'
    end
  end

  resource :session, :only => [:create, :new, :destroy] do
    collection do
      get "new_password_reset"
      post "send_password_reset"
    end
  end
end

app/models/friend_circle.rb
# == Schema Information
#
# Table name: friend_circles
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  name       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class FriendCircle < ActiveRecord::Base
  #:inverse_of => :user
  has_many :friend_circle_memberships,
    :dependent => :destroy,
    :inverse_of => :friend_circle

  has_many(
    :members,
    :through => :friend_circle_memberships,
    :source => :user)

  belongs_to(
    :owner,
    :foreign_key => :user_id,
    :primary_key => :id,
    :class_name => "User")

  validates :owner, :name, :presence => true
end

app/controllers/friend_circles_controller.rb
class FriendCirclesController < ApplicationController

  def new
    @user = User.find(params[:user_id])
    @friend_circle = FriendCircle.new
    render :new
  end

  def create
    @user = User.find(params[:user_id])
    @friend_circle = FriendCircle.new(friend_circle_params)

    if @friend_circle.save
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @friend_circle.errors.full_messages
      render :new
    end
  end

  def edit
    @friend_circle = FriendCircle.find(params[:id])
    @user = @friend_circle.owner
    @members = @friend_circle.members

    render :edit
  end

  def update
    @friend_circle = FriendCircle.find(params[:id])

    if @friend_circle.update_attributes(friend_circle_params)
      redirect_to user_url(@friend_circle.owner)
    else
      flash.now[:errors] = @friend_circle.errors.full_messages
      render :edit
    end
  end

  private

  def friend_circle_params
    params.require(:friend_circle).permit(:name, :user_id, :member_ids => [])
  end
end

app/helpers/friend_circles_helper.rb
module FriendCirclesHelper
end

app/views/friend_circles/_form.html.erb
<% form_action = action == :new ? user_friend_circles_url(@user) :
                                user_friend_circle_url(@user, @friend_circle)%>
<% form_method = action == :new ? 'POST' : 'PATCH' %>
<% form_submit = action == :new ? 'Create Friend Circle' : 'Update Circle' %>


<form action="<%= form_action %>" method="post">
  <input type="hidden" name="authenticity_token"
    value="<%=form_authenticity_token%>">

  <input type="hidden" name="_method" value="<%= form_method %>">

  <input type="hidden" name="friend_circle[user_id]" value="<%= @user.id %>">

  <label for="name">Circle Name</label><input type="text"
      name="friend_circle[name]" value="<%= @friend_circle.name %>" id="name">

  <input type="hidden" name="friend_circle[member_ids][]" value="">

    <%User.all.each do |user|%>
    <label>
      <br>
      <input
        type="checkbox"
        name="friend_circle[member_ids][]"
        value="<%=user.id%>"
        <%if @members.include?(user)%>
         checked
        <% end %>>
        <%=user.email%>
    </label>
    <%end%>

  <p><input type="submit" value="<%= form_submit %>"></p>
</form>

app/views/friend_circles/edit.html.erb
<%= render 'form', :action => :edit%>

app/views/friend_circles/new.html.erb
<form action="<%=user_friend_circles_url(@user)%>" method="post">
  <input type="hidden" name="authenticity_token"
    value="<%=form_authenticity_token%>">

    <input type="hidden" name="friend_circle[user_id]" value="<%= @user.id %>">

    <label for="name">Circle Name</label><input type="text"
      name="friend_circle[name]" id="name">

    <%User.all.each do |user|%>
    <label>
      <br>
      <input
        type="checkbox"
        name="friend_circle[member_ids][]"
        value="<%=user.id%>">
        <%=user.email%>
    </label>
    <%end%>

  <p><input type="submit" value="Create Friend Circle"></p>
</form>