config/routes.rb
SocialThing::Application.routes.draw do

  resources :users, :only => [:create, :new, :show] do
    resources :friend_circles, :only => [:new, :create, :edit, :update]
    resources :posts do
      resources :links, :only => [:create, :destroy]
    end

    member do
      get 'forgot_password'
      get 'feed'
    end
  end

  resource :session, :only => [:create, :new, :destroy] do
    collection do
      get "new_password_reset"
      post "send_password_reset"
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#  reset_token     :string(255)
#

class User < ActiveRecord::Base
  attr_reader :password

  before_validation :ensure_session_token
  before_validation :ensure_password_reset_token
  validates :password_digest, :session_token, :reset_token, :presence => true
  validates :email, :presence => true, :uniqueness => true
  validates :password, :length => { :minimum => 5, :allow_nil => true }

  has_many :posts, :inverse_of => :author, :dependent => :destroy
  has_many :friend_circles, :dependent => :destroy

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def password=(plaintext)
    @password = plaintext
    self.password_digest = BCrypt::Password.create(plaintext)
  end

  def is_password?(plaintext)
    BCrypt::Password.new(self.password_digest).is_password?(plaintext)
  end

  def self.find_by_credentials(email, plaintext)
    user = User.find_by_email(email)
    return nil unless user
    user.is_password?(plaintext) ? user : nil
  end

  private

  def ensure_session_token
    self.session_token = self.class.generate_session_token
  end

  def ensure_password_reset_token
    self.reset_token = self.class.generate_session_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @links = Array.new(3) { Link.new }

    render :new
  end

  def create
    @user = User.new(user_params)
    unless post_params[:body].blank?
      @post = @user.posts.build(post_params)
      @post.links.build(link_params)
    end

    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def forgot_password
    @user = User.find(params[:id])
    if @user.reset_token == params[:token]
      render :forgot_password
    else
      flash[:errors] = "HACKER ALERT!!!"
      redirect_to new_session_url
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :forgot_password
    end
  end

  def feed
    @user = User.find(params[:id])

    @posts = Post.find_by_sql(<<-SQL)
    SELECT DISTINCT
      posts.*
    FROM
      posts
    JOIN post_shares
      ON posts.id = post_shares.post_id
    JOIN friend_circles
      ON post_shares.friend_circle_id = friend_circles.id
    JOIN friend_circle_memberships
      ON friend_circle_memberships.friend_circle_id = friend_circles.id
    WHERE
      friend_circle_memberships.user_id = #{@user.id}
    SQL

    render :feed
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def post_params
    params.require(:user).require(:post).permit(:body)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/feed.html.erb
<%@posts.each do |post|%>
<br>
<%= link_to post.body, user_post_url(post.author, post) %>
<br>
By: <%= post.author.email%>
<%end%>

app/views/users/forgot_password.html.erb
<h1>Reset Password</h1>
<form action="<%= user_url(@user) %>" method="post" accept-charset="utf-8">
  <input type="hidden" name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <input type="hidden" name="_method" value="PATCH">


  <label for="email">Email</label>
  <input type="text" name="user[email]" value="<%= @user.email %>" id="email">

  <label for="password">Password</label>
  <input type="password" name="user[password]" id="password">

  <p><input type="submit" value="Update changes!"></p>
</form>

app/views/users/new.html.erb
<form action="<%= users_url %>" method="post" accept-charset="utf-8">
  <input type="hidden" name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="email">Email</label>
  <input type="text" name="user[email]" value="<%= @user.email %>" id="email">

  <label for="password">Password</label>
  <input type="password" name="user[password]" id="password">

  <p>Create a Post!</p>
  <br>
  <label for="body">Body</label>
  <input type="text" name="user[post][body]" id="body">

  <% @links.each do |link| %>
  <fieldset>
    <label for="url">URL</label><input type="text"
           name="links[url][]" id="url">
  </fieldset>
  <% end %>

  <p><input type="submit" value="Create me!"></p>
</form>

app/views/users/show.html.erb
hi

<%= link_to "Create Friend Circle", new_user_friend_circle_url(@user) %>
<%= link_to "Make Post", new_user_post_url(@user) %>