config/routes.rb
SocialThing::Application.routes.draw do

  resources :users, :only => [:create, :new, :show] do
    resources :friend_circles, :only => [:new, :create, :edit, :update]
    resources :posts do
      resources :links, :only => [:create, :destroy]
    end

    member do
      get 'forgot_password'
      get 'feed'
    end
  end

  resource :session, :only => [:create, :new, :destroy] do
    collection do
      get "new_password_reset"
      post "send_password_reset"
    end
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  body       :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  validates :body, :presence => true

  has_many :links, :inverse_of => :post, :dependent => :destroy
  has_many :post_shares, :inverse_of => :post, :dependent => :destroy
  belongs_to(
    :author,
    :foreign_key => :user_id,
    :primary_key => :id,
    :class_name => "User"
  )

  has_many(
    :friend_circles,
    :through => :post_shares,
    :source => :friend_circle
  )
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @circles = @user.friend_circles
    @post = Post.new
    @links = Array.new(3) { Link.new }

    render :new
  end

  def create
    @user = User.find(params[:user_id])
    @post = Post.new(post_params)
    @post.links.build(link_params)


    if @post.save
      redirect_to user_post_url(@post.author, @post)
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to new_user_post_url
    end
  end

  def show
    @post = Post.find(params[:id])
    @links = @post.links

    render :show
  end


  private

  def post_params
    params.require(:post).permit(:body, :user_id, :friend_circle_ids => [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def link_params
    params.permit(:links => {:url => []})
          .require(:links)
          .values.first
          .reject { |data| data.blank? }
          .map { |data| {:url => data} }
  end
end

app/views/posts/new.html.erb
<form action="<%= user_posts_url(@user) %>" method="post">

  <input type="hidden" name="authenticity_token"
         value="<%= form_authenticity_token %>" id="authenticity_token">

  <input type="hidden" name="post[user_id]" value="<%= @user.id %>">

  <label for="body">Body</label>
  <input type="text" name="post[body]" id="body">

  <% @links.each do |link| %>
  <fieldset>
    <label for="url">URL</label><input type="text" name="links[url][]" id="url">
  </fieldset>
  <% end %>


  <% @circles.each do |circle| %>
  <label>
    <br>
    <input
      type="checkbox"
      name="post[friend_circle_ids][]"
      value="<%=circle.id%>">
      <%=circle.name%>
  </label>
  <%end%>



  <p><input type="submit" value="Continue &darr;"></p>
</form>

app/views/posts/show.html.erb
<%= @post.body %>
<% @links.each do |link| %>
<p><%= link_to link.url, link.url %></p>
<% end %>